var creator = [
    //1-10
    {   
        "pic": "images/homepage/seller1.jpg",
        "collection": "PhantaBear",
        "volume": 19039.49,
        "hours": -7.63,
        "day": +261.30,
        "price": 4,
        "owners": "5.1K",
        "items": "10.0K",
    },
    {   
        "pic": "images/homepage/seller2.jfif",
        "collection": "PhantaBear",
        "volume": 18039.49,
        "hours": -5.68,
        "day": +21.50,
        "price": 1,
        "owners": "3.9K",
        "items": "5.0K",
    },
    {   
        "pic": "images/homepage/seller3.jfif",
        "collection": "PhantaBear",
        "volume": 17089.49,
        "hours": +4.68,
        "day": +21.50,
        "price": 2,
        "owners": "4.9K",
        "items": "5.5K",
    },
    {   
        "pic": "images/homepage/seller4.jpg",
        "collection": "PhantaBear",
        "volume": 17029.49,
        "hours": +3.68,
        "day": -11.50,
        "price": 1.5,
        "owners": "3.1K",
        "items": "4.5K",
    },
    {   
        "pic": "images/homepage/seller5.jfif",
        "collection": "PhantaBear",
        "volume": 16829.49,
        "hours": -5.68,
        "day": -2.50,
        "price": 5.5,
        "owners": "3.0K",
        "items": "4.4K",
    },
    {   
        "pic": "images/homepage/seller6.jpg",
        "collection": "PhantaBear",
        "volume": 16229.49,
        "hours": +3.68,
        "day": -11.50,
        "price": 1.5,
        "owners": "3.1K",
        "items": "4.5K",
    },
    {   
        "pic": "images/homepage/seller7.png",
        "collection": "PhantaBear",
        "volume": 16129.49,
        "hours": +0.68,
        "day": +1.50,
        "price": 1.3,
        "owners": "2.9K",
        "items": "3.5K",
    },
    {   
        "pic": "images/homepage/seller8.png",
        "collection": "PhantaBear",
        "volume": 15129.49,
        "hours": -2.68,
        "day": +1.50,
        "price": 1.3,
        "owners": "3.9K",
        "items": "3.5K",
    },
    {   
        "pic": "images/homepage/seller9.jpg",
        "collection": "PhantaBear",
        "volume": 14529.49,
        "hours": -1.68,
        "day": +1.50,
        "price": 1.0,
        "owners": "3.5K",
        "items": "2.8K",
    },
    {
        "pic": "images/homepage/seller1.jpg",
        "collection": "PhantaBear",
        "volume": 14519.49,
        "hours": +2.68,
        "day": +3.50,
        "price": 1.6,
        "owners": "3.4K",
        "items": "2.1K",
    },
    //11-20
    {   
        "pic": "images/homepage/seller1.jpg",
        "collection": "PhantaBear",
        "volume": 19039.49,
        "hours": -7.63,
        "day": +261.30,
        "price": 4,
        "owners": "5.1K",
        "items": "10.0K",
    },
    {   
        "pic": "images/homepage/seller2.jfif",
        "collection": "PhantaBear",
        "volume": 18039.49,
        "hours": -5.68,
        "day": +21.50,
        "price": 1,
        "owners": "3.9K",
        "items": "5.0K",
    },
    {   
        "pic": "images/homepage/seller3.jfif",
        "collection": "PhantaBear",
        "volume": 17089.49,
        "hours": +4.68,
        "day": +21.50,
        "price": 2,
        "owners": "4.9K",
        "items": "5.5K",
    },
    {   
        "pic": "images/homepage/seller4.jpg",
        "collection": "PhantaBear",
        "volume": 17029.49,
        "hours": +3.68,
        "day": -11.50,
        "price": 1.5,
        "owners": "3.1K",
        "items": "4.5K",
    },
    {   
        "pic": "images/homepage/seller5.jfif",
        "collection": "PhantaBear",
        "volume": 16829.49,
        "hours": -5.68,
        "day": -2.50,
        "price": 5.5,
        "owners": "3.0K",
        "items": "4.4K",
    },
    {   
        "pic": "images/homepage/seller6.jpg",
        "collection": "PhantaBear",
        "volume": 16229.49,
        "hours": +3.68,
        "day": -11.50,
        "price": 1.5,
        "owners": "3.1K",
        "items": "4.5K",
    },
    {   
        "pic": "images/homepage/seller7.png",
        "collection": "PhantaBear",
        "volume": 16129.49,
        "hours": +0.68,
        "day": +1.50,
        "price": 1.3,
        "owners": "2.9K",
        "items": "3.5K",
    },
    {   
        "pic": "images/homepage/seller8.png",
        "collection": "PhantaBear",
        "volume": 15129.49,
        "hours": -2.68,
        "day": +1.50,
        "price": 1.3,
        "owners": "3.9K",
        "items": "3.5K",
    },
    {   
        "pic": "images/homepage/seller9.jpg",
        "collection": "PhantaBear",
        "volume": 14529.49,
        "hours": -1.68,
        "day": +1.50,
        "price": 1.0,
        "owners": "3.5K",
        "items": "2.8K",
    },
    {
        "pic": "images/homepage/seller1.jpg",
        "collection": "PhantaBear",
        "volume": 14519.49,
        "hours": +2.68,
        "day": +3.50,
        "price": 1.6,
        "owners": "3.4K",
        "items": "2.1K",
    },
]

var collection = [
    {
        "pic": "images/homepage/live-gumball.gif",
        "no":"Live Items #689",
        "price":4.2,
        "like":531,
    },
    {
        "pic": "images/homepage/live-licking.gif",
        "no":"Live Items #229",
        "price":2.2,
        "like":511,
    },
    {
        "pic": "images/homepage/live-dip.gif",
        "no":"Live Items #239",
        "price":2.1,
        "like":411,
    },
    {
        "pic": "images/homepage/live-lock.gif",
        "no":"Live Items #329",
        "price":3.1,
        "like":415,
    },
    {
        "pic": "images/status/live-shampoo.gif",
        "no":"Live Items #153",
        "price":3.1,
        "like":415,
    },
    {
        "pic": "images/collections/pencil.gif",
        "no":"Live Items #119",
        "price":2.1,
        "like":205,
    },
    {
        "pic": "images/collections/cheese.gif",
        "no":"Live Items #309",
        "price":2.1,
        "like":205,
    },
    {
        "pic": "images/collections/mask.gif",
        "no":"Live Items #239",
        "price":2.7,
        "like":285,
    },
    {
        "pic": "images/collections/phone.gif",
        "no":"Live Items #319",
        "price":3.1,
        "like":305,
    }
]