document.writeln(' <!-- section5 footer-->');
document.writeln('    <section class="footer">');
document.writeln('        <div class="container">');
document.writeln('            <div class="row">');
document.writeln('                <div class="col-12 col-md-12 col-lg-5">');
document.writeln('                    <div class="item">');
document.writeln('                        <h2>Stay in the loop</h2>');
document.writeln('                        <div class="txt">');
document.writeln('                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum esse ipsam rerum est ullam reiciendis.');
document.writeln('                            </p>');
document.writeln('                            <div class="email">');
document.writeln('                                <input type="text" placeholder="Your email adress">');
document.writeln('                                <button>Sign up</button>');
document.writeln('                            </div>');
document.writeln('                        </div>');
document.writeln('                    </div>');
document.writeln('                </div>');
document.writeln('                <div class="col-12 col-md-12 col-lg-5">');
document.writeln('                    <div class="item">');
document.writeln('                        <h2>Join the Community</h2>');
document.writeln('                        <div class="txt">');
document.writeln('                            ');
document.writeln('                            <ul class="community">');
document.writeln('                                <li><a href="#"><i class="far fa-envelope"></i></a>');
document.writeln('                                </li>');
document.writeln('                                <li><a href="#"><i class="fab fa-twitter"></i></a>');
document.writeln('                                </li>');
document.writeln('                                <li><a href="#"><i class="fab fa-instagram"></i></a>');
document.writeln('                                </li>');
document.writeln('                                <li><a href="#"><i class="fab fa-youtube"></i></a>');
document.writeln('                                </li>');
document.writeln('                            </ul>');
document.writeln('                        </div>');
document.writeln('                    </div>');
document.writeln('                </div>');
document.writeln('            </div>');
document.writeln('            <div class="row">');
document.writeln('                <div class="col-12 col-md-12 col-lg-4">');
document.writeln('                    <div class="item">');
document.writeln('                        <div class="pic">');
document.writeln('                            <img src="images/common/logo.png" alt="" class="footerLogo">');
document.writeln('                        </div>');
document.writeln('                        <div class="txt">');
document.writeln('                           <h2>W-NFTs</h2>');
document.writeln('                           <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere beatae, iste vel unde eligendi eaque.lorem5');
document.writeln('                            ectetur adipisicing');
document.writeln('                           </p>');
document.writeln('                        </div>');
document.writeln('                    </div>');
document.writeln('                </div>');
document.writeln('                <div class="col-6 col-md-6 col-lg-2">');
document.writeln('                    <div class="item footList">');
document.writeln('                        <h4>Marketplace</h4>');
document.writeln('                        <ul>');
document.writeln('                            <li>All NFTs</li>');
document.writeln('                            <li>Art</li>');
document.writeln('                            <li>Music</li>');
document.writeln('                            <li>Domain Names</li>');
document.writeln('                            <li>Virtual Word</li>');
document.writeln('                            <li>Collectibles</li>');
document.writeln('                        </ul>');
document.writeln('                    </div>');
document.writeln('                </div>');
document.writeln('                <div class="col-6 col-md-6 col-lg-2">');
document.writeln('                    <div class="item footList">');
document.writeln('                        <h4>Marketplace</h4>');
document.writeln('                        <ul>');
document.writeln('                            <li>All NFTs</li>');
document.writeln('                            <li>Art</li>');
document.writeln('                            <li>Music</li>');
document.writeln('                            <li>Domain Names</li>');
document.writeln('                            <li>Virtual Word</li>');
document.writeln('                            <li>Collectibles</li>');
document.writeln('                        </ul>');
document.writeln('                    </div>');
document.writeln('                </div>');
document.writeln('                <div class="col-6 col-md-6 col-lg-2">');
document.writeln('                    <div class="item footList">');
document.writeln('                        <h4>Marketplace</h4>');
document.writeln('                        <ul>');
document.writeln('                            <li>All NFTs</li>');
document.writeln('                            <li>Art</li>');
document.writeln('                            <li>Music</li>');
document.writeln('                            <li>Domain Names</li>');
document.writeln('                            <li>Virtual Word</li>');
document.writeln('                            <li>Collectibles</li>');
document.writeln('                        </ul>');
document.writeln('                    </div>');
document.writeln('                </div>');
document.writeln('                <div class="col-6 col-md-6 col-lg-2">');
document.writeln('                    <div class="item footList">');
document.writeln('                        <h4>Marketplace</h4>');
document.writeln('                        <ul>');
document.writeln('                            <li>All NFTs</li>');
document.writeln('                            <li>Art</li>');
document.writeln('                            <li>Music</li>');
document.writeln('                            <li>Domain Names</li>');
document.writeln('                            <li>Virtual Word</li>');
document.writeln('                            <li>Collectibles</li>');
document.writeln('                        </ul>');
document.writeln('                    </div>');
document.writeln('                </div>');
document.writeln('            </div>');
document.writeln('        </div>');
document.writeln('    </section>');
document.writeln('    <!-- copyright -->');
document.writeln('    <section class="copyRight">');
document.writeln('        <div class="container">');
document.writeln('            <div class="row">');
document.writeln('                <div class="col-12 col-md-12 col-lg-10">');
document.writeln('                    <p>M-NFTs ®2021-Tibame Celia</p>');
document.writeln('                    <div class="policy">');
document.writeln('                        <a href="#">Privacy</a>');
document.writeln('                        <a href="#">Term of Service</a>');
document.writeln('                    </div>');
document.writeln('');
document.writeln('                </div>');
document.writeln('                <!-- <div class="col-12 col-md-5 col-lg-5">');
document.writeln('                    <p>我是copyright</p>');
document.writeln('                    <p>我是copyright</p>');
document.writeln('                </div> -->');
document.writeln('            </div>');
document.writeln('        </div>');
document.writeln('    </section>');
